matrix:
  include:
    - language: julia
      julia:
        - 1.0.5
        - nightly
        
    - language: scala
      scala:
        - 2.9.3
        
    - language: ruby
      rvm:
        - 2.6
        - jruby
