matrix:
  include:
    - language: julia
      julia:
        - 1.0.5
        - nightly
        
      script:
        - cd Julia
        - julia --project=docs/ -e 'using Pkg; Pkg.instantiate(); Pkg.develop(PackageSpec(path=pwd()))'
        
    - language: scala
      scala:
        - 2.12.2
        
      jdk:
        - openjdk8
        
      script:
        - cd Scala
        - sbt ++$TRAVIS_SCALA_VERSION compile
        - sbt ++$TRAVIS_SCALA_VERSION test
        
    - language: ruby
      rvm:
        - 2.6
        - jruby
        - truffleruby
