matrix:
  include:
    - language: julia
      julia:
        - 1.0.5
        - nightly
        
    - language: scala
      scala:
        - 2.9.3
        
      jdk:
        - oraclejdk8
        - openjdk7
        - openjdk6
        
      script:
        - cd build-sbt
        - sbt ++$TRAVIS_SCALA_VERSION test
        
    - language: ruby
      rvm:
        - 2.6
        - jruby
        - truffleruby
